### ISSUE TITLE
todo-list for draft/metadata-2 tests

### ISSUE THREAD

**Issue by progval** [progval/irctest#195]
In this branch: https://github.com/progval/irctest/compare/metadata2?expand=1 (no PR because it would be noisy)

* [ ] SUB before connect
* [ ] UNSUB
* [ ] SYNC
* [ ] rate-limiting
* [ ] quote a spec paragraph in every docstring
* [ ] CI on Github (pull https://github.com/progval/unrealircd-contrib/blob/metadata2/files/metadata2.c )

**Comment by slingamn** [comment]
- [ ] test case normalization of keys
- [ ] "If the key is valid, but not set, and the client tries to remove the key, the server responds with FAIL METADATA KEY_NOT_SET and fails the request."
